{
  "spring": {
    "application": {
      "name": "postgres-student-api"
    },
    "jpa": {
      "hibernate": {
        "ddl-auto": "update"
      },
      "database-platform": "org.hibernate.dialect.PostgreSQLDialect",
      "show-sql": false,
      "open-in-view": false
    },
    "datasource": {
      "url": "jdbc:postgresql://localhost:5432/university",
      "hikari": {
        "maximumPoolSize": 2,
        "connectionTestQuery": "SELECT 1",
        "maxLifetime": 180000
      },
      "username": "postgres",
      "password": "123"
    }
  },
  "springdoc": {
    "swagger-ui": {
      "disable-swagger-default-url": false
    }
  },
  "management": {
    "endpoints": {
      "web": {
        "exposure": {
          "include": "health,prometheus"
        }
      }
    },
    "metrics": {
      "export": {
        "prometheus": {
          "enabled": true
        }
      },
      "distribution": {
        "percentiles-histogram": {
          "[http.server.requests]": true
        }
      }
    }
  }
}